services:
  backend:
    build:
      context: ./youtube-stats-backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "7543:7543"
    environment:
      NODE_ENV: development
    restart: always

  frontend:
    build:
      context: ./youtube-stats
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "5173:5173"
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
    driver: local
